version: '3'
services:
  app:
    image: flask_app
    container_name: flask_app
    restart: unless-stopped
    build:
      context: .
      dockerfile: app/Dockerfile
    environment:
      DB_PASSWORD: 6yamim1967
      DB_USERNAME: root
    depends_on:
      - mysql
    ports:
      - "5000:5000"
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    build: ./db/
    environment:
      MYSQL_ROOT_PASSWORD: '6yamim1967'
      MYSQL_DATABASE: 'dbcard'
      MYSQL_HOST: 'mysql'

    ports:
      - "3306:3306"